# Generated by Django 4.1.1 on 2022-11-02 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_tax'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='fooditem',
            new_name='productitem',
        ),
    ]
